### ISSUE TITLE
2.1.1 no longer works with file-fetch

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/fetch-lite#14]
I think that the logic introduced in #13 is unnecessarily strict and specific. Because of that `dataset()` is never added to responses from [file-fetch](https://www.npmjs.com/package/file-fetch)

Would it be enough to check whether `res.body` is defined?

**Comment by tpluscode** [comment]
> Would it be enough to check whether res.body is defined?

Guess not. So maybe file-fetch should set the `content-length` header?

**Comment by bergos** [comment]
Added `content-length` header support in 1.7.0 of  `file-fetch.` That should solve the problem.
