### ISSUE TITLE
Separate entry point for browsers

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/fetch-lite#20]
It does not make sense to bundle `nodeify-fetch` when building a web application.

I would like to propose a PR where we split the exports, using built-in `window.fetch` in browser environment. All build toolsets should support that:

```json
{
  "main": "index.js",
  "browser": "browser.js"
}
```

I see that the `Factory.js` module makes refactoring slightly more complicated, hence I'm submitting a PR straight away. What do you think?

**Comment by bergos** [comment]
`nodeify-fetch` does that already, and it's required in the browser environment. `nodeify-fetch` takes care of converting the WHATWG streams to Node streams used by the parsers.

I will close this issue. Feel free to leave a comment if I missed something important. Then I would open the issue again.
